/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIsta;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author LaptopSA
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        CheckPrincipal = new javax.swing.JCheckBox();
        CheckSecundaria = new javax.swing.JCheckBox();
        comboTipoMed = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        fondoxd = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Nombre de Medicamento");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 28));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tipo de Medicamento");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 28));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Cantidad que requiere");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 28));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("SUCURSAL");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 28));

        txtNombre.setToolTipText("INGRESE EL NOMBRE DEL MEDICAMENTO");
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 222, -1));

        txtCantidad.setToolTipText("INGRESE EL NOMBRE DEL MEDICAMENTO");
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 222, -1));

        Grupo1.add(radio1);
        radio1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radio1.setText("COFARMA");
        getContentPane().add(radio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        Grupo1.add(radio2);
        radio2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radio2.setText("EMPSEPHAR");
        radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio2ActionPerformed(evt);
            }
        });
        getContentPane().add(radio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        Grupo1.add(radio3);
        radio3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radio3.setText("CEMEFAR");
        getContentPane().add(radio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("DISTRIBUIDOR");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 28));

        CheckPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckPrincipal.setText("PRINCIPAL");
        getContentPane().add(CheckPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        CheckSecundaria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckSecundaria.setText("SECUNDARIA");
        CheckSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckSecundariaActionPerformed(evt);
            }
        });
        getContentPane().add(CheckSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        getContentPane().add(comboTipoMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 259, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("FARMACIA");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 28));

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAceptar.setText("OK");
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        fondoxd.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout fondoxdLayout = new javax.swing.GroupLayout(fondoxd);
        fondoxd.setLayout(fondoxdLayout);
        fondoxdLayout.setHorizontalGroup(
            fondoxdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        fondoxdLayout.setVerticalGroup(
            fondoxdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(fondoxd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CheckSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckSecundariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckSecundariaActionPerformed

    private void radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio2ActionPerformed

    public JCheckBox getCheckPrincipal() {
        return CheckPrincipal;
    }

    public void setCheckPrincipal(JCheckBox CheckPrincipal) {
        this.CheckPrincipal = CheckPrincipal;
    }

    public JCheckBox getCheckSecundaria() {
        return CheckSecundaria;
    }

    public void setCheckSecundaria(JCheckBox CheckSecundaria) {
        this.CheckSecundaria = CheckSecundaria;
    }

    public ButtonGroup getGrupo1() {
        return Grupo1;
    }

    public void setGrupo1(ButtonGroup Grupo1) {
        this.Grupo1 = Grupo1;
    }

    public JComboBox<String> getComboTipoMed() {
        return comboTipoMed;
    }

    public void setComboTipoMed(JComboBox<String> comboTipoMed) {
        this.comboTipoMed = comboTipoMed;
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }
    
    public JPanel getFondoxd() {
        return fondoxd;
    }

    public void setFondoxd(JPanel fondoxd) {
        this.fondoxd = fondoxd;
    }

    public JRadioButton getRadio1() {
        return radio1;
    }

    public void setRadio1(JRadioButton radio1) {
        this.radio1 = radio1;
    }

    public JRadioButton getRadio2() {
        return radio2;
    }

    public void setRadio2(JRadioButton radio2) {
        this.radio2 = radio2;
    }

    public JRadioButton getRadio3() {
        return radio3;
    }

    public void setRadio3(JRadioButton radio3) {
        this.radio3 = radio3;
    }

    public JTextField getTxtCantidad() {
        return txtCantidad;
    }

    public void setTxtCantidad(JTextField txtCantidad) {
        this.txtCantidad = txtCantidad;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckPrincipal;
    private javax.swing.JCheckBox CheckSecundaria;
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> comboTipoMed;
    private javax.swing.JPanel fondoxd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
